// old-project/src/components/Navbar.tsx
'use client';

import Link from 'next/link';
import { useState } from 'react';

export default function Navbar() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <nav className="bg-white shadow-md">
      <div className="container-custom py-4">
        <div className="flex justify-between items-center">
          <div className="flex items-center">
            <Link href="/" className="text-2xl font-bold text-blue-600">
              מכירת חמץ אונליין
            </Link>
          </div>
          
          {/* תפריט למסכים גדולים */}
          <div className="hidden md:flex space-x-8">
            <Link href="/" className="text-gray-700 hover:text-blue-600 text-lg font-medium">
              דף הבית
            </Link>
            <Link href="/about" className="text-gray-700 hover:text-blue-600 text-lg font-medium">
              אודות
            </Link>
            <Link href="/form" className="text-gray-700 hover:text-blue-600 text-lg font-medium">
              טופס מכירה
            </Link>
          </div>
          
          {/* תפריט למכשירים ניידים */}
          <div className="md:hidden">
            <button
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              className="text-gray-700 hover:text-blue-600"
              aria-label="תפריט"
            >
              {isMenuOpen ? (
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" className="h-6 w-6">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" className="h-6 w-6">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              )}
            </button>
          </div>
        </div>
        
        {/* תפריט נפתח למכשירים ניידים */}
        {isMenuOpen && (
          <div className="md:hidden mt-4 pb-4 space-y-3">
            <Link href="/" 
                  onClick={() => setIsMenuOpen(false)}
                  className="block py-2 px-4 text-center text-gray-700 hover:bg-blue-50 rounded-md">
              דף הבית
            </Link>
            <Link href="/about"
                  onClick={() => setIsMenuOpen(false)}
                  className="block py-2 px-4 text-center text-gray-700 hover:bg-blue-50 rounded-md">
              אודות
            </Link>
            <Link href="/form"
                  onClick={() => setIsMenuOpen(false)}
                  className="block py-2 px-4 text-center text-gray-700 hover:bg-blue-50 rounded-md">
              טופס מכירה
            </Link>
          </div>
        )}
      </div>
    </nav>
  );
}

// src/components/Navbar.vue
<template>
  <nav class="sticky top-0 z-40 transition-all duration-300"
    :class="scrolled ? 'bg-white/90 backdrop-blur-md shadow-lg shadow-primary-900/5' : 'bg-white/70 backdrop-blur-sm'">
    <div class="container-custom">
      <div class="flex justify-between items-center py-3">
        <router-link to="/" class="flex items-center gap-2 group">
          <span class="text-2xl">🌾</span>
          <span class="font-bold text-xl text-primary-800 group-hover:text-primary-600 transition-colors duration-300">
            מכירת חמץ
          </span>
        </router-link>

        <div class="hidden md:flex items-center gap-1">
          <router-link to="/" class="nav-link" active-class="nav-link-active">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            דף הבית
          </router-link>
          <router-link to="/form" class="nav-link" active-class="nav-link-active">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            מכירת חמץ
          </router-link>
          <router-link to="/kimcha" class="nav-link nav-link-green" active-class="nav-link-active-green">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            קמחא דפסחא
          </router-link>
          <!-- <a href="https://63863ecdd7031.site123.me/" class="nav-link" target="_blank">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            אתר הארגון
          </a> -->
        </div>

        <div class="md:hidden">
          <button @click="toggleMenu"
            class="text-gray-700 hover:text-primary-600 focus:outline-none p-2 rounded-xl hover:bg-primary-50 transition-all duration-200">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path v-if="!menuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M4 6h16M4 12h16M4 18h16" />
              <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      <!-- Mobile Menu -->
      <transition name="mobile-menu">
        <div v-if="menuOpen" class="md:hidden pb-4 border-t border-primary-100/50">
          <div class="pt-3 space-y-1">
            <router-link to="/" class="mobile-nav-link" @click="menuOpen = false">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-3" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
              דף הבית
            </router-link>
            <router-link to="/form" class="mobile-nav-link" @click="menuOpen = false">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-3" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              מכירת חמץ
            </router-link>
            <router-link to="/kimcha" class="mobile-nav-link" @click="menuOpen = false">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-3" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              קמחא דפסחא
            </router-link>
            <!-- <a href="https://63863ecdd7031.site123.me/" class="mobile-nav-link" target="_blank"
              @click="menuOpen = false">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-3" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              אתר הארגון
            </a> -->
          </div>
        </div>
      </transition>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navbar',
  data() {
    return {
      menuOpen: false,
      scrolled: false
    }
  },
  mounted() {
    window.addEventListener('scroll', this.handleScroll)
  },
  beforeUnmount() {
    window.removeEventListener('scroll', this.handleScroll)
  },
  methods: {
    toggleMenu() {
      this.menuOpen = !this.menuOpen
    },
    handleScroll() {
      this.scrolled = window.scrollY > 20
    }
  }
}
</script>

<style scoped>
.nav-link {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.5rem 0.875rem;
  border-radius: 0.75rem;
  font-weight: 500;
  font-size: 0.9rem;
  color: #57534e;
  transition: all 0.2s ease;
}

.nav-link:hover {
  color: #b45309;
  background-color: rgba(245, 158, 11, 0.08);
}

.nav-link-active {
  color: #92400e !important;
  background-color: rgba(245, 158, 11, 0.12) !important;
  font-weight: 600;
}

.nav-link-green:hover {
  color: #059669;
  background-color: rgba(16, 185, 129, 0.08);
}

.nav-link-active-green {
  color: #047857 !important;
  background-color: rgba(16, 185, 129, 0.12) !important;
  font-weight: 600;
}

.mobile-nav-link {
  display: flex;
  align-items: center;
  padding: 0.75rem 1rem;
  border-radius: 0.75rem;
  color: #57534e;
  font-weight: 500;
  transition: all 0.2s ease;
}

.mobile-nav-link:hover {
  background-color: rgba(245, 158, 11, 0.06);
  color: #b45309;
}

/* Mobile menu transition */
.mobile-menu-enter-active,
.mobile-menu-leave-active {
  transition: all 0.3s ease;
  max-height: 300px;
  overflow: hidden;
}

.mobile-menu-enter-from,
.mobile-menu-leave-to {
  opacity: 0;
  max-height: 0;
}
</style>
